### ISSUE TITLE
SpaceNet 7: Multi-Temporal Urban Development Challenge ~10GB

### ISSUE THREAD

**Issue by andreaschandra** [jakartaresearch/earth-vision#19]
Add research dataset to benchmark machine learning task
Primarly picked from https://github.com/chrieke/awesome-satellite-imagery-datasets#1-instance-segmentation

- [SpaceNet 7: Multi-Temporal Urban Development Challenge](https://spacenet.ai/sn7-challenge/) (CosmiQ Works, Planet, Aug 2020)
Monthly building footprints and Planet imagery (4m. res) timeseries for 2 years, 100 locations around the globe, for building footprint evolution & address propagation.

https://medium.com/the-downlinq/the-spacenet-7-multi-temporal-urban-development-challenge-dataset-release-9e6e5f65c8d5

**Comment by rubentea16** [comment]
@gilangarisptr kita bakal lanjut ngerjain ini yaa

**Comment by rubentea16** [comment]
https://github.com/avanetten/CosmiQ_SN7_Baseline

**Comment by rubentea16** [comment]
sample dataset : 
- gs://ossjr/sample_SN7_buildings_train.tar.gz
- gs://ossjr/sample_SN7_buildings_test_public.tar.gz
