### ISSUE TITLE
Deepsat: SAT-4/SAT-6 airborne 2.4GB

### ISSUE THREAD

**Issue by andreaschandra** [jakartaresearch/earth-vision#30]
Scene Classification

- [Deepsat: SAT-4/SAT-6 airborne datasets (Louisiana State University, 2015)](https://csc.lsu.edu/~saikat/deepsat/)
6 land cover categories, 400k 28x28 pixel chips, 4-band RGBNIR aerial imagery (1m res.) extracted from the 2009 National Agriculture Imagery Program (NAIP), Paper: Basu et al. 2015

**Comment by rubentea16** [comment]
@gilangarisptr take a look at this
