### ISSUE TITLE
UC Merced Land Use 300MB

### ISSUE THREAD

**Issue by andreaschandra** [jakartaresearch/earth-vision#31]
Scene Classification

- [UC Merced Land Use Dataset (UC Merced, Oct 2010)](http://weegee.vision.ucmerced.edu/datasets/landuse.html)
21 land cover categories from agricultural to parkinglot, 100 chips per class, aerial imagery (0.30m res.), Paper: Yang & Newsam 2010

To Do:
- [ ] Dataset Class
- [ ] Downloader

**Comment by andreaschandra** [comment]
how was the test going? @FendiSuryadinata570

**Comment by FendiSuryadinata570** [comment]
On Progress
