### ISSUE TITLE
38-Cloud: A Cloud Segmentation Dataset 16GB

### ISSUE THREAD

**Issue by andreaschandra** [jakartaresearch/earth-vision#36]
Instance Segmentation

- [38-Cloud: A Cloud Segmentation Dataset (S. Mohajerani et. all, Jan 2020)](https://github.com/SorourMo/38-Cloud-A-Cloud-Segmentation-Dataset)

**Comment by rubentea16** [comment]
@rubentea16 create sample dataset

**Comment by rubentea16** [comment]
sample dataset: gs://ossjr/38cloud.zip
