### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by andreaschandra** [jakartaresearch/earth-vision#38]
add contributing guidelines

- coding style
- rules
- formatting

Reference: https://github.com/pytorch/vision/blob/master/CONTRIBUTING.md

**Comment by andreaschandra** [comment]
which formatter guys @rubentea16 @juannat95  [flake8](https://flake8.pycqa.org/en/latest/) atau [pycodestyle](https://pycodestyle.pycqa.org/en/latest/intro.html) ?

**Comment by andreaschandra** [comment]
and using [pydocstyle](https://www.pydocstyle.org/en/2.1.1/usage.html#cli-usage) for docstring?

**Comment by rubentea16** [comment]
> which formatter guys @rubentea16 @juannat95 [flake8](https://flake8.pycqa.org/en/latest/) atau [pycodestyle](https://pycodestyle.pycqa.org/en/latest/intro.html) ?

pycodestyle sama pydocstyle sih
