### ISSUE TITLE
So2Sat LCZ42 52GB

### ISSUE THREAD

**Issue by andreaschandra** [jakartaresearch/earth-vision#48]
So2Sat LCZ42 is a dataset consisting of co-registered synthetic aperture radar and multispectral optical image patches acquired by the Sentinel-1 and Sentinel-2 remote sensing satellites, and the corresponding local climate zones (LCZ) label. The dataset is distributed over 42 cities across different continents and cultural regions of the world. 

[Download](https://mediatum.ub.tum.de/1454690)

**Comment by andreaschandra** [comment]
how's the sample? @juannat7

**Comment by juannat7** [comment]
https://storage.googleapis.com/ossjr/so2sat.zip
