### ISSUE TITLE
Landsat 8 Cloud Cover 

### ISSUE THREAD

**Issue by juannat7** [jakartaresearch/earth-vision#55]
Landsat 8 Cloud Cover: https://landsat.usgs.gov/landsat-8-cloud-cover-assessment-validation-data

**Comment by andreaschandra** [comment]
having trouble in reading `BC/LC80420082013220LGN00/LC80420082013220LGN00_fixedmask.img`

```
---------------------------------------------------------------------------
UnidentifiedImageError                    Traceback (most recent call last)
<ipython-input-2-1cb99b7275b9> in <module>
----> 1 Image.open("BC/LC80420082013220LGN00/LC80420082013220LGN00_fixedmask.img")

~/miniconda3/lib/python3.8/site-packages/PIL/Image.py in open(fp, mode, formats)
   2965     for message in accept_warnings:
   2966         warnings.warn(message)
-> 2967     raise UnidentifiedImageError(
   2968         "cannot identify image file %r" % (filename if filename else fp)
   2969     )

UnidentifiedImageError: cannot identify image file 'BC/LC80420082013220LGN00/LC80420082013220LGN00_fixedmask.img'
```

**Comment by andreaschandra** [comment]
@juannat7 baca mask nya ENVI file ga bisa pake either matplotlib/Pillow ya

**Comment by juannat7** [comment]
Yea, kayaknya harus pake spectral package (https://stackoverflow.com/questions/45178549/reading-img-envi-file-with-spectral-python).

**Comment by andreaschandra** [comment]
Yea, gua udah coba, errornya masih sama pake spectral

**Comment by andreaschandra** [comment]
@rubentea16

**Comment by rubentea16** [comment]
### SOLVED

![image](https://user-images.githubusercontent.com/46805454/127695945-46624bd8-3327-43e8-ab6d-7eb4c1952f80.png)
![image](https://user-images.githubusercontent.com/46805454/127695071-fc58bd0e-0009-414d-b591-20ffad874da1.png)
![image](https://user-images.githubusercontent.com/46805454/127695096-e71c214d-baeb-46d1-a023-fd70b25c57a1.png)

Read HDR File nya guys ~ raw raster filenya itu yg extension `.img`
![image](https://user-images.githubusercontent.com/46805454/127695361-cbc64f31-78a0-4b22-aadf-1de493a9b7cc.png)


https://github.com/spectralpython/spectral/blob/master/spectral/io/envi.py#L45
![image](https://user-images.githubusercontent.com/46805454/127695567-c730cf89-475b-421f-b9cb-a5c0585a9c8d.png)

@andreaschandra @juannat7
