### ISSUE TITLE
Update Documentation on pdoc

### ISSUE THREAD

**Issue by andreaschandra** [jakartaresearch/earth-vision#79]
Update docstring and pdoc

https://github.com/pdoc3/pdoc

**Comment by rubentea16** [comment]
branch `gh-pages` @adhiiisetiawan @dewabratapandu

**Comment by rubentea16** [comment]
@rubentea16 

TODO:
- update README.md
- update class docstring (wrong way of writing)
- Add file docstring (inconsistency)
